# Generated by Django 2.1.2 on 2019-03-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloseFitMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('c_20', models.CharField(max_length=20, verbose_name='our reference')),
                ('c_21', models.CharField(max_length=20, null=True, verbose_name='previous reference')),
                ('c_22A', models.CharField(max_length=10, null=True, verbose_name='type of operation')),
                ('c_22C', models.CharField(max_length=20, null=True, verbose_name='common reference')),
                ('c_94A', models.CharField(max_length=30, null=True, verbose_name='scope of operation')),
                ('c_82', models.CharField(max_length=20, verbose_name='party a')),
                ('c_87', models.CharField(max_length=20, verbose_name='party b')),
                ('c_77H', models.DateField(verbose_name='isda date')),
                ('c_52A', models.CharField(max_length=20, null=True, verbose_name='unknown info')),
                ('c_30T', models.DateField(verbose_name='contract date')),
                ('c_30V', models.DateField(verbose_name='value date')),
                ('c_36', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='exchange_rate')),
                ('c_32B_fi', models.CharField(max_length=5, null=True, verbose_name='currency to buy')),
                ('c_32B_se', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='amount of currency to buy')),
                ('c_33B_fi', models.CharField(max_length=5, null=True, verbose_name='currency to sell')),
                ('c_33B_se', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='amount of currency to sell')),
                ('c_53', models.CharField(max_length=20, verbose_name='delivery agent')),
                ('c_56', models.CharField(blank=True, default='', max_length=20, verbose_name='intermediary')),
                ('c_57', models.CharField(max_length=20, verbose_name='settlement')),
                ('c_58', models.CharField(max_length=20, verbose_name='beneficiary')),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('c_20', models.CharField(max_length=20, verbose_name='our reference')),
                ('c_21', models.CharField(max_length=20, null=True, verbose_name='previous reference')),
                ('c_22A', models.CharField(max_length=10, null=True, verbose_name='type of operation')),
                ('c_22C', models.CharField(max_length=20, null=True, verbose_name='common reference')),
                ('c_94A', models.CharField(max_length=30, null=True, verbose_name='scope of operation')),
                ('c_82', models.CharField(max_length=20, verbose_name='party a')),
                ('c_87', models.CharField(max_length=20, verbose_name='party b')),
                ('c_77H', models.DateField(verbose_name='isda date')),
                ('c_52A', models.CharField(max_length=20, null=True, verbose_name='unknown info')),
                ('c_30T', models.DateField(verbose_name='contract date')),
                ('c_30V', models.DateField(verbose_name='value date')),
                ('c_36', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='exchange_rate')),
                ('c_32B_fi', models.CharField(max_length=5, null=True, verbose_name='currency to buy')),
                ('c_32B_se', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='amount of currency to buy')),
                ('c_33B_fi', models.CharField(max_length=5, null=True, verbose_name='currency to sell')),
                ('c_33B_se', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='amount of currency to sell')),
                ('c_53', models.CharField(max_length=20, verbose_name='delivery agent')),
                ('c_56', models.CharField(blank=True, default='', max_length=20, verbose_name='intermediary')),
                ('c_57', models.CharField(max_length=20, verbose_name='settlement')),
                ('c_58', models.CharField(max_length=20, verbose_name='beneficiary')),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneToManyMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OneToOneMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt300.MessageCP')),
                ('sg_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt300.MessageSG')),
            ],
        ),
        migrations.AddField(
            model_name='closefitmatches',
            name='cp_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt300.MessageCP'),
        ),
        migrations.AddField(
            model_name='closefitmatches',
            name='sg_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt300.MessageSG'),
        ),
    ]
