# Generated by Django 2.1.2 on 2019-03-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt300', '0002_auto_20190316_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagecp',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='messagesg',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='messagecp',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Un-matched'), ('closefit', 'CloseFit'), ('under-review', 'Under Review'), ('unreviewed', 'Unreviewed')], default='unmatched', max_length=30),
        ),
        migrations.AddField(
            model_name='messagesg',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Un-matched'), ('closefit', 'CloseFit'), ('under-review', 'Under Review'), ('unreviewed', 'Unreviewed')], default='unmatched', max_length=30),
        ),
    ]
