# Generated by Django 2.1.2 on 2019-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt300', '0004_onetoonematches_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='closefitmatches',
            name='remark',
            field=models.CharField(default='', max_length=100),
        ),
    ]
